# Generated by Django 4.1.5 on 2023-01-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('cod_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('rutDocente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellidoP', models.TextField(max_length=50)),
                ('apellidoM', models.TextField(max_length=50)),
                ('sexo', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Academico',
            fields=[
                ('cod_nivelA', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.asignaturas')),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.nivel_academico')),
                ('rutDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('rutAlumno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellidoP', models.TextField(max_length=50)),
                ('apellidoM', models.TextField(max_length=50)),
                ('sexo', models.TextField(max_length=50)),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colegio.nivel_academico')),
            ],
        ),
    ]
