# Generated by Django 4.1.5 on 2023-01-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colegio', '0002_alter_asignaturas_cod_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_academico',
            name='cod_nivelA',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
